# Generated by Django 3.2.23 on 2024-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dwsdsw', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
